name: Let's Encrypt
description: Trusted SSL certificates at zero cost
version: 1.0.0
category: Security
maintainer: HaiNguyen007 
license: Apache License 2.0
projectURL:://github.com/HaiNguyen007/my-rancher-catalog.git 
